-- =============================================================================
-- MatrAI — Supabase Database Migration
-- Run this script in the Supabase SQL Editor (or via supabase CLI migrations)
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "pgcrypto";   -- provides gen_random_uuid()

-- ---------------------------------------------------------------------------
-- ENUM: risk_level
-- ---------------------------------------------------------------------------
DO $$ BEGIN
    CREATE TYPE risk_level AS ENUM ('RED', 'YELLOW', 'GREEN');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- ===========================================================================
-- TABLE: users
-- ===========================================================================
CREATE TABLE IF NOT EXISTS users (
    id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    phone            TEXT        NOT NULL UNIQUE,
    language         TEXT        NOT NULL DEFAULT 'en',
    consent_given    BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  users                IS 'Registered MatrAI users identified by phone number.';
COMMENT ON COLUMN users.phone          IS 'E.164 formatted phone number — must be unique.';
COMMENT ON COLUMN users.language       IS 'Preferred language code, e.g. en, hi, ta.';
COMMENT ON COLUMN users.consent_given  IS 'Whether the user has given informed consent.';

-- Index for fast phone-based lookups
CREATE INDEX IF NOT EXISTS idx_users_phone ON users (phone);

-- Row Level Security
ALTER TABLE users ENABLE ROW LEVEL SECURITY;


-- ===========================================================================
-- TABLE: pregnancies
-- ===========================================================================
CREATE TABLE IF NOT EXISTS pregnancies (
    id                     UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    gestational_weeks      INT         CHECK (gestational_weeks BETWEEN 0 AND 45),
    last_menstrual_period  DATE,
    is_active              BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  pregnancies                       IS 'Pregnancy records linked to a user. A user may have multiple, but only one should be active.';
COMMENT ON COLUMN pregnancies.gestational_weeks     IS 'Current gestational age in weeks (0–45).';
COMMENT ON COLUMN pregnancies.last_menstrual_period IS 'Date of the last menstrual period used to calculate gestational age.';
COMMENT ON COLUMN pregnancies.is_active             IS 'TRUE for the currently active pregnancy.';

-- Only one active pregnancy per user (partial unique index)
CREATE UNIQUE INDEX IF NOT EXISTS idx_pregnancies_active_user
    ON pregnancies (user_id)
    WHERE is_active = TRUE;

CREATE INDEX IF NOT EXISTS idx_pregnancies_user_id ON pregnancies (user_id);

ALTER TABLE pregnancies ENABLE ROW LEVEL SECURITY;


-- ===========================================================================
-- TABLE: calls
-- ===========================================================================
CREATE TABLE IF NOT EXISTS calls (
    id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id        UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    risk_level     risk_level,
    symptoms_json  JSONB,
    transcript     TEXT,
    ai_advice      TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  calls               IS 'Records of AI-assisted health calls placed by users.';
COMMENT ON COLUMN calls.risk_level    IS 'Triage result: RED (emergency), YELLOW (moderate), GREEN (safe).';
COMMENT ON COLUMN calls.symptoms_json IS 'Structured symptom data captured during the call.';
COMMENT ON COLUMN calls.transcript    IS 'Full conversation transcript from the call.';
COMMENT ON COLUMN calls.ai_advice     IS 'Advice generated by the AI during the call.';

CREATE INDEX IF NOT EXISTS idx_calls_user_id    ON calls (user_id);
CREATE INDEX IF NOT EXISTS idx_calls_risk_level ON calls (risk_level);
-- GIN index for fast JSONB queries on symptoms
CREATE INDEX IF NOT EXISTS idx_calls_symptoms   ON calls USING GIN (symptoms_json);

ALTER TABLE calls ENABLE ROW LEVEL SECURITY;


-- ===========================================================================
-- TABLE: emergency_logs
-- ===========================================================================
CREATE TABLE IF NOT EXISTS emergency_logs (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    call_id         UUID        NOT NULL REFERENCES calls (id) ON DELETE CASCADE,
    user_id         UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    notified_asha   BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  emergency_logs                IS 'Audit log of emergency notifications triggered from high-risk calls.';
COMMENT ON COLUMN emergency_logs.call_id        IS 'The call that triggered this emergency log.';
COMMENT ON COLUMN emergency_logs.notified_asha  IS 'Whether the local ASHA worker was notified.';

CREATE INDEX IF NOT EXISTS idx_emergency_logs_call_id ON emergency_logs (call_id);
CREATE INDEX IF NOT EXISTS idx_emergency_logs_user_id ON emergency_logs (user_id);

ALTER TABLE emergency_logs ENABLE ROW LEVEL SECURITY;


-- ===========================================================================
-- OPTIONAL: Basic RLS Policies
-- (Adjust to match your auth strategy — service-role key bypasses RLS)
-- ===========================================================================

-- Users can read/update only their own row
CREATE POLICY "users_self_access" ON users
    FOR ALL USING (auth.uid() = id);

-- Users can access only their own pregnancies
CREATE POLICY "pregnancies_owner_access" ON pregnancies
    FOR ALL USING (auth.uid() = user_id);

-- Users can access only their own calls
CREATE POLICY "calls_owner_access" ON calls
    FOR ALL USING (auth.uid() = user_id);

-- Users can view their own emergency logs
CREATE POLICY "emergency_logs_owner_access" ON emergency_logs
    FOR ALL USING (auth.uid() = user_id);
